\c boston_public_schools_db;

CREATE TABLE buildings (
    OBJECTID_1 SERIAL,
    OBJECTID INTEGER,
    BLDG_ID INTEGER,
    BLDG_NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    ZIPCODE VARCHAR(10),
    CSP_SCH_ID INTEGER,
    SCH_ID INTEGER,
    SCH_NAME VARCHAR(255),
    SCH_LABEL VARCHAR(100),
    SCH_TYPE VARCHAR(50),
    SHARED VARCHAR(50),
    COMPLEX VARCHAR(50),
    Label INTEGER,
    TLT INTEGER,
    PL VARCHAR(100),
    POINT_X DOUBLE PRECISION,
    POINT_Y DOUBLE PRECISION,
    geom GEOMETRY(Point, 4326)
);
